@startuml

object "Monitor" as Monitor {
  id: string
  name: string
  email: string
  phone: string
}

object "Preset" as Preset {
  id: string
  name: string
  description: string
  monitor: Monitor
}

Preset::monitor --> Monitor : Belong to

@enduml