@startuml
' testdot
skinparam style strictuml
skinparam DefaultFontName Arial

class "Monitor" as Monitor {
  id: string
  name: string
  email: string
  phone: string
}

class "Preset" as Preset {
  id: string
  name: string
  description: string
  monitor: Monitor
}
@enduml