@startuml Pitchtrack

skinparam style strictuml
skinparam DefaultFontName Arial

object Slot {
  _id: string,
  title: string,
  speaker: string,
  notes: string,
  startType: Manual | Auto,
  startDate: dd-mm-yyyy,
  startTime: hh:mm,
  endTime: hh:mm,
  duration: hh:mm:ss,
  appearance: CountDown | CountUp,
  message: 'This is a message',
  warningTime: mm:ss,
  dangerTime: mm:ss,
  warningColor: string,
  dangerColor: string,
  warningSound: string,
  dangerSound: string,
  flash: boolean,
  flashCount: number,
  sortOrder: 1,
  status: Active | Inactive,
  startCountAt: hh:mm:ss,
  event: Event.object.ref,
}

object Event {
  title: string,
  isrunning: boolean,
  user: User.object.ref,
  slots: [Slot.object.ref],
  messages: [Message.object.ref],
}

object Message {
  message: string,
  color: White | Green | Red,
  weight: Normal | Bold,
  cap: Boolean,
  event: Event.object.ref,
}

object User {
  _id: ObjectId,
  name: string,
  email: string,
  password: string,
  role: Organizer | Speaker,
  events: [Event.object.ref]
}

@enduml